version: "3"
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - mynet
    volumes:
      - ~/Library/Containers/com.docker.docker/Data/vms/db:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
  nginx:
    restart: unless-stopped
    image: evansariel/nginx:latest
    container_name: nginx
    networks:
      - mynet
    ports:
      - 80:80
      - 443:443
    volumes:
        - /Applications/MAMP/htdocs:/projects
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./log/nginx:/var/log/nginx
  php74:
    #build: ./files/php/
    image: evansariel/php74:latest
    container_name: php74
    restart: unless-stopped
    networks:
      - mynet
    volumes:
      - /Applications/MAMP/htdocs:/projects
    depends_on:
      - mysql
    environment:
      DB_ROOT_PW: "1234"
networks:
  mynet:
    external: true
