version: "3"
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - mynet
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
  nginx:
    restart: unless-stopped
    image: evansariel/nginx:latest
    container_name: nginx
    networks:
      - mynet
    ports:
      - 80:80
      - 443:443
    volumes:
        - /Applications/MAMP/htdocs:/projects
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./log/nginx:/var/log/nginx
  php-8:
    build: ./docker/php-8/build
    image: php-8
    restart: unless-stopped
    env_file:
      - mysql.env
    networks:
      - mynet
    depends_on:
      - mysql
    environment:
      DB_ROOT_PW: "1234"
    volumes:
      - /Applications/MAMP/htdocs:/projects
      - ./docker/php-8/config/msmtprc:/etc/msmtprc:ro
      - ./docker/php-8/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
      - ./docker/php-8/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-8/composer/:/root/.composer/
      - ./projects/:/srv/projects/
    logging: *default-logging
networks:
  mynet:
    external: true
